feat: add polygon mapper
b-partners/geo-jobs pull request #212
Opened 2024-06-30 19:38 UTC by Dinasoa

2024-07-01 06:06 UTC, NyH1409 requested changes

2024-07-01 06:06 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/FeatureMapper.java
> +        System.out.println("Taille d'un ring: " + ring.size());
remove "System.out.println", use `@Slf4j` if necessary

2024-07-01 06:06 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/FeatureMapper.java
> +    if (multiPolygonCoordinates != null && !multiPolygonCoordinates.isEmpty()) {
throw exception immediatly on empty or null

2024-07-01 06:06 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/FeatureMapper.java
> +      List<List<List<BigDecimal>>> polygon = multiPolygonCoordinates.get(0);
suspicious. Use getFirst() if really necessary

2024-07-01 06:06 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/FeatureMapper.java
> +          BigDecimal x = ring.get(i).get(0);
getFirst()

2024-07-01 06:06 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/FeatureMapper.java
> +          BigDecimal y = ring.get(i).get(1);
getLast() as ring size is equal to 2

2024-07-01 08:02 UTC, NyH1409 requested changes

2024-07-01 08:02 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/FeatureMapper.java
> +    for (List<List<BigDecimal>> ring : polygon) {
Use for each instead

2024-07-02 11:54 UTC, bp-lou approved these changes

2024-07-02 11:54 UTC, bp-lou commented on doc/api.yml
> +  '/parcelize':
No! Never use a verb as endpoint! Create nouns and objects, eg: parcelization

2024-07-02 11:54 UTC, bp-lou commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/FeatureMapper.java
> +
superfluous empty line

2024-07-02 12:33 UTC, merged