fix: security issues sonar exception
b-partners/geo-jobs pull request #215
Opened 2024-07-02 11:51 UTC by nirinaHelena

2024-07-10 14:15 UTC, hei-teacher requested changes

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileUnzipperTest.java
> +          + File.separator
well, no. just "/" is enough

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileUnzipperTest.java
> +    } catch (IOException e) {
useless. you already throws IOException in your signature

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileUnzipperTest.java
> +  ZipFile zipFile() throws IOException {
bad name. You are not constructing a standard zipFile. You are constructing a MALICIOUS zipFile (which contains path traversal attack with ".."). Make it explicit in the name

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileWriterTest.java
> +    byte[] bytes = new byte[] {1, 2, 3};
var

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileWriterTest.java
> +    File directory = null;
bad. use null directly where needed

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileWriterTest.java
> +    byte[] bytes = new byte[] {1, 2, 3};
var

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileWriterTest.java
> +    File invalidDirectory = new File("../");
var

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileWriterTest.java
> +    String filename = "testfile";
var

2024-07-10 14:15 UTC, hei-teacher commented on src/test/java/app/bpartners/geojobs/unit/FileWriterTest.java
> +    byte[] bytes = new byte[] {1, 2, 3};
var everywhere possible

2024-07-25 08:44 UTC, NyH1409 requested changes

2024-07-25 08:44 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/file/FileWriter.java
> +      throw new IllegalArgumentException("name must not contain .. but receceived: pathValue");
what is `pathValue`?

2024-07-26 06:30 UTC, NyH1409 approved these changes

2024-07-26 07:45 UTC, merged