feat: implement detection endpoint
b-partners/geo-jobs pull request #228
Opened 2024-07-16 11:29 UTC by Dinasoa

2024-07-17 13:52 UTC, hei-teacher requested changes

2024-07-17 13:52 UTC, hei-teacher commented on doc/api.yml
> +        - HUMAN
HUMAN_DETECTION

2024-07-17 13:52 UTC, hei-teacher commented on doc/api.yml
> +        - MACHINE
MACHINE_DETECTION

2024-07-17 13:52 UTC, hei-teacher commented on doc/api.yml
> +        geojsonUrl:
detectedGeojsonUrl

2024-07-17 13:52 UTC, hei-teacher commented on doc/api.yml
> +           $ref: '#/components/schemas/Type'
Type of what !!! Jesus, can you stop being so NOT explicit!!!

2024-07-17 13:52 UTC, hei-teacher commented on doc/api.yml
> +  '/detection':
FullDetection. And use that name everywhere

2024-07-23 05:30 UTC, hei-ryan requested changes

2024-07-23 05:30 UTC, hei-ryan commented on .gitignore
> +venv/
Why ?

2024-07-23 05:30 UTC, hei-ryan commented on .gitignore
> +.DS_Store
No

2024-07-31 07:07 UTC, NyH1409 requested changes

2024-07-31 07:07 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/TilingTaskCreated.java
> +  public TilingTaskCreated(TilingTask task) {
Is this really required?I don't think so

2024-07-31 07:07 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/TilingTaskCreated.java
> +  private CreateFullDetection fullDetection;
Do not forget to add `@JsonProperty("")` for consistency

2024-07-31 07:07 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/TilingTaskSucceeded.java
> +  private TilingTaskSucceeded(TilingTask tilingTask) {
same

2024-07-31 07:07 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/TilingTaskFailed.java
> +  private CreateFullDetection createFullDetection;
same

2024-07-31 07:07 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/ZTJStatusRecomputingSubmitted.java
> +  private CreateFullDetection createFullDetection;
make it `final`

2024-07-31 07:07 UTC, nvagno commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/ZoneTilingJobCreated.java
> +  public ZoneTilingJobCreated(ZoneTilingJob zoneTilingJob) {
why?

2024-07-31 07:07 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/DetectableObjectConfigurationMapper.java
> +        .confidence(rest.getConfidence() != null ? rest.getConfidence().doubleValue() : 1)
what is this magic number `1`?

2024-07-31 07:07 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/DetectableObjectConfigurationMapper.java
> +                ? BigDecimal.valueOf(1)
put `1` in a static variable `DEFAULT_CONFIDENCE` for example

2024-07-31 07:07 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/service/ZoneService.java
> +  public boolean isPending(ZoneDetectionJob job) {
No need. I think this method already exists for a job: `job.isPending()`

2024-07-31 07:07 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/service/event/TileDetectionTaskSucceededService.java
> +  private boolean isFinished(List<TileDetectionTask> tasks) {
Create it in the `Task` class if not exists

2024-07-31 07:07 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/service/event/ZDJStatusRecomputingSubmittedService.java
> +    if (FINISHED.equals(jobStatus.getProgression()) && SUCCEEDED.equals(jobStatus.getHealth())) {
replace with `zoneDetectionJob.isSucceeded()`

2024-07-31 07:07 UTC, NyH1409 commented on src/main/java/app/bpartners/geojobs/service/event/ZTJStatusRecomputingSubmittedService.java
> +    if (FINISHED.equals(jobStatus.getProgression()) && SUCCEEDED.equals(jobStatus.getHealth())) {
same

2024-07-31 10:47 UTC, hei-ryan reviewed
Globally, I don't know where do you persist the fullDetection entity ?

2024-07-31 10:47 UTC, hei-ryan commented on .gitignore
> -.DS_Store
Don't touch

2024-07-31 10:47 UTC, hei-ryan commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/ZTJStatusRecomputingSubmitted.java
> +  private CreateFullDetection createFullDetection;
Why did you resolve without making it final ?

2024-07-31 10:47 UTC, hei-ryan commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/mapper/DetectableObjectConfigurationMapper.java
> +  public static String BUCKET_STORAGE_NAME = "TILING_IMAGES";
Why is it a constant inside the code here ?

2024-07-31 10:47 UTC, hei-ryan commented on src/main/resources/db/migration/V43_50__Create_full_detection_table.sql
> +);
Undo it

2024-07-31 10:47 UTC, hei-ryan commented on src/main/java/app/bpartners/geojobs/endpoint/rest/controller/ZoneDetectionController.java
> +  public FullDetectedZone processFullDetection(@RequestBody CreateFullDetection zoneToDetect) {
Don't forget to add a validator for rest CreateFullDetection

2024-07-31 10:47 UTC, hei-ryan commented on src/main/resources/db/migration/V43_53__Update_ZTJ_and_ZDJ_table.sql
> +alter table if exists zone_tiling_job add column if not exists end_to_end_id varchar;
End to end ID is used when the ZTJ or ZDJ has to be exposed outside the geo-jobs api. 

Here, it's the full detection ID that must have an end to end it, not the ZTJ or the ZDJ. 

The client doesn't know and SHOULD NOT know, the domain ids, other than the end to end ID.

What you must do then is to just associate the fullDetection entity with the ZTJ and same for ZDJ

2024-07-31 10:47 UTC, hei-ryan commented on src/main/java/app/bpartners/geojobs/endpoint/event/model/TilingTaskCreated.java
> +  private CreateFullDetection fullDetection;
No. 

The FullDetection must be persisted when the request is handled, and if necessary, get it from the ZTJ attributes associated to the TilingTask, not directly here. Can you explicit why do we need it here ?

2024-07-31 10:47 UTC, hei-ryan commented on src/main/java/app/bpartners/geojobs/repository/ZoneTilingJobRepository.java
> +  ZoneTilingJob findByEndToEndId(String endToEndId);
No.

2024-08-02 09:46 UTC, merged